// This file was auto generated by the Rust app. Do not modify it.


type HashSet<T extends number | string> = Record<T, undefined>;type HashMap<T extends number | string, U> = Record<T, U>;type Vec<T> = Array<T>;type Option<T> = T | undefined;type Result<T, U> = T | U;type RustFunctionCreator<Args, Return> = { args: Args; return: Return };export interface TodoItem{id:number;content:string;completed:boolean;};

export type RustFunction = {get_todo_items: RustFunctionCreator<never, Vec<TodoItem>>, add_todo_item: RustFunctionCreator<{content: string, }, Result<[],string>>, toggle_todo_item: RustFunctionCreator<{id: number, }, void>, remove_todo_item: RustFunctionCreator<{id: number, }, void>, }