// This file was auto generated by the Rust app. Do not modify it.


type HashSet<T extends number | string> = Record<T, undefined>;type HashMap<T extends number | string, U> = Record<T, U>;type Vec<T> = Array<T>;type Option<T> = T | undefined;type Result<T, U> = T | U;type RustFunctionCreator<Args, Return, Error> = { args: Args; return: Return; error: Error };export interface TodoItem{id:number;content:string;completed:boolean;};

export type RustFunction = {get_todo_items: RustFunctionCreator<never, Vec<TodoItem>, never>, add_todo_item: RustFunctionCreator<{content: string, }, [], string>, toggle_todo_item: RustFunctionCreator<{id: number, }, void, never>, remove_todo_item: RustFunctionCreator<{id: number, }, void, never>, }